### ISSUE TITLE
Update repo security.

### ISSUE THREAD

**Issue by janiversen** [pymodbus-dev/pymodbus#1517]
Something is configured wrong in security, committers (people with write bit) should be able to merge a PR.

Demand is:
- write bit
- Branch based on newest dev
- CI green

**Comment by janiversen** [comment]
@alexrudd2 can you please check, that you can merge a pull request now (I removed the demand for approval).

**Comment by janiversen** [comment]
btw. if you are co-authoring a PR, you cannot approve it, that is standard GitHub security.

**Comment by alexrudd2** [comment]
I don't have access to the Branch protection rules (which is fine), but I can guess as to the settings.  Note: the screenshots below are from another repo and don't show current values!

> write bit

Enabled already.

> Branch based on newest dev

I don't understand how, but I think this one works already?  Just to be explicit, you always use **Squash and merge**, right?  (The alternative is **rebase and merge**)
![Screenshot 2023-04-25 at 9 48 24 AM](https://user-images.githubusercontent.com/52292902/234315049-aadaddc7-359f-489f-b09f-6380d242217f.png)

> CI green

Doesn't appear to be enabled
![Screenshot 2023-04-25 at 9 49 04 AM](https://user-images.githubusercontent.com/52292902/234315293-0198e336-22ce-4946-9ddd-8f38e0a75868.png)

 > ~~Review approval~~

I believe you were previously able to bypass the requirement of approval because you're an administrator.
![Screenshot 2023-04-25 at 9 44 14 AM](https://user-images.githubusercontent.com/52292902/234313806-d9db539e-bc13-4865-9529-8a6ad406e064.png)

Anyways, it's disabled now.  https://github.com/pymodbus-dev/pymodbus/pull/1520 worked for me.

**Comment by janiversen** [comment]
Please always use squash and merge. Your write bit allows you to merge PR, but not maintain the repo (settings).

I had to disable the CI green (or at least I think so) to ensure you can merge. However that is not a problem if we both are a bit careful.

**Comment by alexrudd2** [comment]
> I had to disable the CI green (or at least I think so) to ensure you can merge. However that is not a problem if we both are a bit careful.

Hmm, I don't think this was necessary.  CI green should be a different status check than requiring review.

I think the below settings are what you want (although you'll have to change **test-python**)
![Screenshot 2023-04-25 at 10 47 13 AM](https://user-images.githubusercontent.com/52292902/234332121-91caae91-ebc6-4bd5-9d6d-a13ce30531d6.png)

**Comment by janiversen** [comment]
Got it to work....you need a status check on top of "require branches...". It works now.
